### ISSUE TITLE
error occurred first time I attacked a MOB

### ISSUE THREAD

**Issue by j3b4** [PlanetPath/Public#1]
The initial message included the following at the top:

`Error in menu node 'menunode_apply_bonus'.`

After the full traceback I had no commands besides "help" available so I reloaded the client and came ooc to the account screen.  I tried IC my character and got the following traceback:

```
Traceback (most recent call last):
  File "c:\users\riane\documents\mygame\evennia\evennia\commands\cmdhandler.py", line 631, in _run_command
    ret = cmd.func()
  File "c:\users\riane\documents\mygame\evennia\evennia\commands\default\account.py", line 325, in func
    account.puppet_object(session, new_character)
  File "c:\users\riane\documents\mygame\evennia\evennia\accounts\accounts.py", line 314, in puppet_object
    obj.at_pre_puppet(self, session=session)
  File "c:\users\riane\documents\mygame\evennia\evennia\objects\objects.py", line 2152, in at_pre_puppet
    self.location.at_object_receive(
  File "C:\Users\riane\Documents\mygame\mygameUnbound\typeclasses\rooms.py", line 184, in at_object_receive
    item.at_char_entered(obj)
  File "C:\Users\riane\Documents\mygame\mygameUnbound\typeclasses\mobs.py", line 368, in at_char_entered
    if not enter_tag in target.tags.all(): # player has not been seen before
AttributeError: 'NoneType' object has no attribute 'tags'

An untrapped error occurred.
(Traceback was logged 20-09-12 21:26:17-06).
```

**Comment by j3b4** [comment]
I'm sorry I didn't capture much from the initial error.  I'm pretty sleepy.  I'm certainly intrigued by your game though. I look forward to investigating further.  Also I'm so impressed that you developed a thing!  Cheers.

**Comment by j3b4** [comment]
Okay got it again - right after choosing to allocate my psi power clairvoyance to "hit"
```
                                                                              
Defense: Apply bonus to defense                      
Hit: Apply bonus to hit chance for psyche abilities  
Healing: Apply bonus to psyche ability healing       
Damage: Apply bonus to psyche ability damage         
Error in menu node 'menunode_apply_bonus'.
Traceback (most recent call last):
  File "c:\users\riane\documents\mygame\evennia\evennia\commands\cmdhandler.py", line 759, in cmdhandler
    raise ExecSystemCommand(syscmd, sysarg)
evennia.commands.cmdhandler.ExecSystemCommand: (<evennia.utils.evmenu.CmdEvMenuNode object at 0x00C2E3A0>, 'hit')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\riane\documents\mygame\evennia\evennia\commands\cmdhandler.py", line 631, in _run_command
    ret = cmd.func()
  File "c:\users\riane\documents\mygame\evennia\evennia\utils\evmenu.py", line 294, in func
    menu.parse_input(self.raw_string)
  File "c:\users\riane\documents\mygame\evennia\evennia\utils\evmenu.py", line 992, in parse_input
    self.run_exec_then_goto(execfunc, goto, raw_string, exec_kwargs, goto_kwargs)
  File "c:\users\riane\documents\mygame\evennia\evennia\utils\evmenu.py", line 897, in run_exec_then_goto
    self.goto(goto, raw_string, **(goto_kwargs if goto_kwargs else {}))
  File "c:\users\riane\documents\mygame\evennia\evennia\utils\evmenu.py", line 812, in goto
    nodetext, options = self._execute_node(nodename, raw_string, **kwargs)
  File "c:\users\riane\documents\mygame\evennia\evennia\utils\evmenu.py", line 661, in _execute_node
    ret = self._safe_call(node, raw_string, **kwargs)
  File "c:\users\riane\documents\mygame\evennia\evennia\utils\evmenu.py", line 620, in _safe_call
    ret = callback(self.caller, raw_string, **kwargs)
  File "C:\Users\riane\Documents\mygame\mygameUnbound\typeclasses\combat.py", line 1915, in menunode_apply_bonus
    profession_combat = combat_psionic.prefight_bonus(target, caller, result)
TypeError: prefight_bonus() missing 1 required positional argument: 'text'

An untrapped error occurred.
(Traceback was logged 20-09-12 21:57:31-06).
Traceback (most recent call last):
  File "c:\users\riane\documents\mygame\evennia\evennia\commands\cmdhandler.py", line 759, in cmdhandler
    raise ExecSystemCommand(syscmd, sysarg)
evennia.commands.cmdhandler.ExecSystemCommand: (<evennia.utils.evmenu.CmdEvMenuNode object at 0x00C2E3A0>, 'hit')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\riane\documents\mygame\evennia\evennia\commands\cmdhandler.py", line 631, in _run_command
    ret = cmd.func()
  File "c:\users\riane\documents\mygame\evennia\evennia\utils\evmenu.py", line 294, in func
    menu.parse_input(self.raw_string)
  File "c:\users\riane\documents\mygame\evennia\evennia\utils\evmenu.py", line 992, in parse_input
    self.run_exec_then_goto(execfunc, goto, raw_string, exec_kwargs, goto_kwargs)
  File "c:\users\riane\documents\mygame\evennia\evennia\utils\evmenu.py", line 897, in run_exec_then_goto
    self.goto(goto, raw_string, **(goto_kwargs if goto_kwargs else {}))
  File "c:\users\riane\documents\mygame\evennia\evennia\utils\evmenu.py", line 812, in goto
    nodetext, options = self._execute_node(nodename, raw_string, **kwargs)
  File "c:\users\riane\documents\mygame\evennia\evennia\utils\evmenu.py", line 661, in _execute_node
    ret = self._safe_call(node, raw_string, **kwargs)
  File "c:\users\riane\documents\mygame\evennia\evennia\utils\evmenu.py", line 620, in _safe_call
    ret = callback(self.caller, raw_string, **kwargs)
  File "C:\Users\riane\Documents\mygame\mygameUnbound\typeclasses\combat.py", line 1915, in menunode_apply_bonus
    profession_combat = combat_psionic.prefight_bonus(target, caller, result)
TypeError: prefight_bonus() missing 1 required positional argument: 'text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\riane\documents\mygame\evennia\evennia\commands\cmdhandler.py", line 789, in cmdhandler
    ret = yield _run_command(
evennia.commands.cmdhandler.ErrorReported: hit

A command handler bug occurred. If this is not due to a local change,
please file a bug report with the Evennia project, including the
traceback and steps to reproduce.
(Traceback was logged 20-09-12 21:57:31-06).
```
